### ISSUE TITLE
thoughtviz_with_label.py: Parameters to the generator constructor

### ISSUE THREAD

**Issue by virresh** [ptirupat/ThoughtViz#1]
Hello,
While trying to replicate the results, I had made the following minor changes to the repository: 
https://github.com/ptirupat/ThoughtViz/compare/master...virresh:master

But I couldn't find any reference to the gan training through conditioning via labels (hopefully that's what `thoughtviz_with_label.py` does) in the paper. Thus I am struggling a bit to find the correct parameters into the generator for that file (i.e line https://github.com/ptirupat/ThoughtViz/blob/master/training/thoughtviz_with_label.py#L39)

If I run the code without changes, I get an error that the generator class needs two arguments.

On doing changes as per [this](https://github.com/ptirupat/ThoughtViz/compare/master...virresh:master#diff-e337dcd686e863009f80bf5d5d3db2cb), I get the error as:

```
Epoch is  0
Number of batches 76
Traceback (most recent call last):
  File "thoughtviz_with_label.py", line 120, in <module>
    train()
  File "thoughtviz_with_label.py", line 116, in train
    train_gan(dataset=dataset, input_noise_dim=100, batch_size=batch_size, epochs=epochs, model_save_dir=model_save_dir, output_dir=output_dir, classifier_model_file=classifier_model_file)
  File "thoughtviz_with_label.py", line 72, in train_gan
    generated_images = g.predict(conditioned_noise, verbose=0)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training_utils.py", line 102, in standardize_input_data
    str(len(data)) + ' arrays: ' + str(data)[:200] + '...')
ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), but instead got the following list of 1 arrays: [array([[-0.8185435 ,  0.81783497,  0.85355677, ...,  0.        ,
         0.        ,  0.        ],
       [ 0.26742367, -0.47361484, -0.16795557, ...,  0.        ,
         0.        ,  1.        ],...
```

Any help would be much appreciated

**Comment by ptirupat** [comment]
I made changes to the file and it should probably fix this issue. I did not test the changes. Please check.
